#!/bin/bash

### Define the installation directory.
export INSTALL_PATH="/home/mix/Mixproxy"
### Script options. There should be only minor changes here.
export PROGRAM_NAME="mix"
export PROGRAM="$PROGRAM_NAME"
export PROGRAM_OPTIONS="--config=$INSTALL_PATH/config.xml"
export COMPILE_OPTIONS="--with-pools --with-xml-include=/usr/local/xerces-c/include/ --with-xml-lib=/usr/local/xerces-c/lib/"
#export COMPILE_OPTIONS="--enable-crime-detection --with-pools --with-xml-include=/usr/local/xerces-c/include/ --with-xml-lib=/usr/local/xerces-c/lib/"
#export COMPILE_OPTIONS="--enable-debug --with-pools --with-xml-include=/usr/local/xerces-c/include/ --with-xml-lib=/usr/local/xerces-c/lib/"
export EXECUTE_COMMAND=""
export LOGFILE="$INSTALL_PATH/messages"
export VERSION_OPTION="-version"
export CVS_MODULE="proxytest"
export CVSROOT=":pserver:anonymous@cvs.inf.tu-dresden.de:/home/sk13/cvssource"

### Call the common start script
$INSTALL_PATH/../runANONServer $*
